### ISSUE TITLE
Изучение GitHub API

### ISSUE THREAD

**Issue by apellpro** [apellpro/vvpd-project#3]
# Изучение GitHub API

## Описание проблемы
Для работы с информацией о репозиториях необходимо изучить документацию к API GitHub.

**Comment by NikMatyukhin** [comment]
Также, неплохо бы было написать либо программный модуль, позволяющий доставать данные на ваше усмотрение из Github, либо создать [Postman Collection](https://docs.microsoft.com/ru-ru/connectors/custom-connectors/create-postman-collection). После, эту коллекцию можно было бы разместить где-нибудь в директории проекта в директории .postman/ или типа того
